### ISSUE TITLE
Ensure iOS 8.0 compatibility

### ISSUE THREAD

**Issue by weshenderson** [Factual/engine-braze-integration-ios#9]
See https://github.com/Factual/PartnerServices/issues/13602#issuecomment-474405836

**Comment by weshenderson** [comment]
@CMBleakley assigning to @nnlamb25

**Comment by CMBleakley** [comment]
👍

**Comment by nnlamb25** [comment]
Just confirmed that the integration works on 8.0
The simulator was running 8.1 because there's no version lower than that available, but the deployment target was 8.0 and everything was working fine.

Also just an FYI, in the integration docs the [Usage Requirements section](https://github.com/Factual/engine-braze-integration-ios#usage-requirements) the link for configuring Engine is dead.

**Comment by weshenderson** [comment]
@nnlamb25 before we can close this, we also need to set the iOS deployment target to 8.0 in the Xcode project. The deployment target setting is what causes the warning for Hearst. Can you do this?

**Comment by nnlamb25** [comment]
@weshenderson I've changed the deployment target to 8.0

**Comment by weshenderson** [comment]
@nnlamb25 OK sounds good. Closing.
